"""empty message

Revision ID: c236b373c308
Revises: 
Create Date: 2022-11-08 19:25:53.390583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c236b373c308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reptiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=50), nullable=True),
    sa.Column('scientific_name', sa.String(length=50), nullable=True),
    sa.Column('conservation_status', sa.String(length=50), nullable=True),
    sa.Column('native_habitat', sa.String(length=50), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reptiles')
    # ### end Alembic commands ###
